### ISSUE TITLE
Exception due to incomplete expression in __init__.py

### ISSUE THREAD

**Issue by tayjaybabee** [Inspyre-Softworks/inSPy-Logger#1]
Due to the following lines in inspy_logger/\_\_init\_\_.py:
https://github.com/Inspyre-Softworks/inSPy-Logger/blob/6e6086e3f9dc7148082b115c709025634ae33f3d/inspy_logger/__init__.py#L125-L127

```python

>>> import inspy_logger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/taylor/.src/.pyenv/versions/3.6.3/lib/python3.6/site-packages/inspy_logger/__init__.py", line 125
    self.manifest += 'root': {
                           ^
SyntaxError: invalid syntax

```

--------

**Dev Comment:**
    This is a fragment of incomplete code that got committed by mistake. Commenting out and then recommitting.

**Comment by tayjaybabee** [comment]
This will be fixed with PR #4
